config/routes.rb
require 'constraints/domain_constraint'

Rails.application.routes.draw do
  devise_for :users
  post '/webhooks/:source', to: 'webhooks#create'

  constraints DomainConstraint do
    scope module: :stores do
      resources :products
      root to: 'products#index', as: 'store_root'
      resource :checkout, as: 'store_checkout'
      resources :logins
      resources :orders
      resources :attachments
    end
  end

  root 'static_pages#root'

  resource :dashboard
  resources :accounts
  resources :payouts, only: [:create, :index]
  resources :payments, only: [:index, :show]

  resources :products do
    resources :attachments, shallow: true
  end

  resource :store

  resource :checkout
  resources :customers
  resources :cardholders do
    resources :cards, shallow: true do
      resource :ephemeral_key, only: [:show]
    end
  end
end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id              :bigint           not null, primary key
#  domain          :string
#  primary_color   :string
#  secondary_color :string
#  subdomain       :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :bigint           not null
#
# Indexes
#
#  index_stores_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Store < ApplicationRecord
  belongs_to :user
  has_many :products, through: :user
  has_many :customers, through: :products

  def self.find_by_request(request)
    puts "Finding by request"

    where(domain: request.domain)
      .or(where(subdomain: request.subdomain))
      .first
  end
end

app/controllers/stores/attachments_controller.rb
module Stores
  class AttachmentsController < StoreBaseController
    before_action :authenticate_customer!

    def show
      @attachment = current_customer.attachments.find(params[:id])

      send_data(
        @attachment.file.download,
        filename: @attachment.file.filename.to_s,
      )
    end
  end
end

app/controllers/stores/checkouts_controller.rb
module Stores
  class CheckoutsController < StoreBaseController

    def show
      @checkout_session = Stripe::Checkout::Session.retrieve({
        id: params[:session_id],
        expand: ['line_items.data.price.product', 'payment_intent.payment_method']
      }, {
        stripe_account: @store.user.account.stripe_id
      })
    end

    def create
      checkout_session = Stripe::Checkout::Session.create({
        mode: 'payment',
        success_url: store_checkout_url + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url: store_root_url,
        line_items: [{
          price: params[:price],
          quantity: 1
        }]
      }, {
        stripe_account: @store.user.account.stripe_id
      })

      redirect_to checkout_session.url, allow_other_host: true, status: :see_other
    end
  end
end

app/controllers/stores/logins_controller.rb
module Stores
  class LoginsController < StoreBaseController
    def index
      render plain: "Check your email."
    end

    def show
      @customer = current_store.customers.find_by(session_token: params[:id])
      if @customer
        session[:customer] = @customer.session_token
      end

      if params[:redirect_path]
        redirect_to params[:redirect_path]
      else
        redirect_to orders_path
      end
    end

    def new
    end

    def create
      customer = current_store.customers.find_by(email: params[:email])

      if customer
        LoginLinkMailer.send_link(customer, current_store).deliver_later
      end

      redirect_to logins_path
    end
  end
end

app/controllers/stores/orders_controller.rb
module Stores
  class OrdersController < StoreBaseController
    before_action :authenticate_customer!

    def index
      @orders = current_customer.customer_products.order(created_at: :desc)
    end

    def show
      @order = current_customer.customer_products.find(params[:id])
      @product = @order.product
    end
  end
end

app/controllers/stores/products_controller.rb
module Stores
  class ProductsController < StoreBaseController
    def index
      @products = @store.products
    end

    def show
      @product = @store.products.find(params[:id])
    end
  end
end

app/controllers/stores/store_base_controller.rb
module Stores
  class StoreBaseController < ApplicationController
    layout 'stores'
    before_action :current_store

    def current_store
      @store ||= Store.find_by_request(request)
    end

    def authenticate_customer!
      if current_customer.nil?
        redirect_to new_login_path
      end
    end

    def current_customer
      @current_customer ||= Customer.where(
        session_token: session[:customer],
        token_expires_at: Time.now..
      ).first
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!
  layout 'application'

  def show
    @store = current_user.store
  end

  def edit
    @store = current_user.store
  end

  def update
    @store = current_user.store
    if @store.update(store_params)
      service = StripeAccount.new(current_user.account)
      service.update_account_branding
      redirect_to store_path
    else
      render :edit
    end
  end

  private

  def store_params
    params.require(:store).permit(
      :domain,
      :subdomain,
      :primary_color,
      :secondary_color
    )
  end
end

app/helpers/stores/attachments_helper.rb
module Stores::AttachmentsHelper
end

app/helpers/stores/checkouts_helper.rb
module Stores::CheckoutsHelper
end

app/helpers/stores/logins_helper.rb
module Stores::LoginsHelper
end

app/helpers/stores/orders_helper.rb
module Stores::OrdersHelper
end

app/helpers/stores/products_helper.rb
module Stores::ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/orders/index.html.erb
<h2 class="text-2xl font-extrabold tracking-tight text-gray-900">
  Orders
</h2>

<div class="px-4 sm:px-6 lg:px-8">
  <div class="mt-8 flex flex-col">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Product</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">Edit</span>
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
              <% @orders.each do |order| %>
                <tr>
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                    <%= order.id %>
                  </td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                    <%= order.product.name %>
                  </td>
                  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                    <a href="<%= order_path(order) %>" class="text-blue-600 hover:text-blue-900">
                      View
                    </a>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stores/orders/show.html.erb
<h2 class="text-2xl font-extrabold tracking-tight text-gray-900">
  Order <%= @order.id %>
</h2>


<div class="flex mt-8">

  <div>
    <%= image_tag @product.photo.representation(:medium) %>
  </div>

  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="flex-auto px-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-xl font-semibold text-gray-900">Attachments</h1>
        <p class="mt-2 text-sm text-gray-700">A list of all the attachments that you can download.</p>
      </div>
      <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      </div>
    </div>
    <div class="mt-8 flex flex-col">
      <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
          <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
            <table class="min-w-full divide-y divide-gray-300">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
                  <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                    <span class="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 bg-white">
                <% @product.attachments.each do |attachment| %>
                <tr>
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                    <%= attachment.name %>
                  </td>
                  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                    <a href="<%= attachment_path(attachment) %>" class="text-blue-600 hover:text-blue-900">
                      Download
                    </a>
                  </td>
                </tr>
                <% end %>
                <!-- More people... -->
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>