config/routes.rb
require 'constraints/domain_constraint'

Rails.application.routes.draw do
  devise_for :users
  post '/webhooks/:source', to: 'webhooks#create'

  constraints DomainConstraint do
    scope module: :stores do
      resources :products
      root to: 'products#index', as: 'store_root'
      resource :checkout, as: 'store_checkout'
      resources :logins
      resources :orders
      resources :attachments
    end
  end

  root 'static_pages#root'

  resource :dashboard
  resources :accounts
  resources :payouts, only: [:create, :index]
  resources :payments, only: [:index, :show]

  resources :products do
    resources :attachments, shallow: true
  end

  resource :store

  resource :checkout
  resources :customers
  resources :cardholders do
    resources :cards, shallow: true do
      resource :ephemeral_key, only: [:show]
    end
  end
end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id              :bigint           not null, primary key
#  domain          :string
#  primary_color   :string
#  secondary_color :string
#  subdomain       :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :bigint           not null
#
# Indexes
#
#  index_stores_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Store < ApplicationRecord
  belongs_to :user
  has_many :products, through: :user
  has_many :customers, through: :products

  def self.find_by_request(request)
    puts "Finding by request"

    where(domain: request.domain)
      .or(where(subdomain: request.subdomain))
      .first
  end
end

app/controllers/stores/attachments_controller.rb
module Stores
  class AttachmentsController < StoreBaseController
    before_action :authenticate_customer!

    def show
      @attachment = current_customer.attachments.find(params[:id])

      send_data(
        @attachment.file.download,
        filename: @attachment.file.filename.to_s,
      )
    end
  end
end

app/controllers/stores/checkouts_controller.rb
module Stores
  class CheckoutsController < StoreBaseController

    def show
      @checkout_session = Stripe::Checkout::Session.retrieve({
        id: params[:session_id],
        expand: ['line_items.data.price.product', 'payment_intent.payment_method']
      }, {
        stripe_account: @store.user.account.stripe_id
      })
    end

    def create
      checkout_session = Stripe::Checkout::Session.create({
        mode: 'payment',
        success_url: store_checkout_url + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url: store_root_url,
        line_items: [{
          price: params[:price],
          quantity: 1
        }]
      }, {
        stripe_account: @store.user.account.stripe_id
      })

      redirect_to checkout_session.url, allow_other_host: true, status: :see_other
    end
  end
end

app/controllers/stores/logins_controller.rb
module Stores
  class LoginsController < StoreBaseController
    def index
      render plain: "Check your email."
    end

    def show
      @customer = current_store.customers.find_by(session_token: params[:id])
      if @customer
        session[:customer] = @customer.session_token
      end

      if params[:redirect_path]
        redirect_to params[:redirect_path]
      else
        redirect_to orders_path
      end
    end

    def new
    end

    def create
      customer = current_store.customers.find_by(email: params[:email])

      if customer
        LoginLinkMailer.send_link(customer, current_store).deliver_later
      end

      redirect_to logins_path
    end
  end
end

app/controllers/stores/orders_controller.rb
module Stores
  class OrdersController < StoreBaseController
    before_action :authenticate_customer!

    def index
      @orders = current_customer.customer_products.order(created_at: :desc)
    end

    def show
      @order = current_customer.customer_products.find(params[:id])
      @product = @order.product
    end
  end
end

app/controllers/stores/products_controller.rb
module Stores
  class ProductsController < StoreBaseController
    def index
      @products = @store.products
    end

    def show
      @product = @store.products.find(params[:id])
    end
  end
end

app/controllers/stores/store_base_controller.rb
module Stores
  class StoreBaseController < ApplicationController
    layout 'stores'
    before_action :current_store

    def current_store
      @store ||= Store.find_by_request(request)
    end

    def authenticate_customer!
      if current_customer.nil?
        redirect_to new_login_path
      end
    end

    def current_customer
      @current_customer ||= Customer.where(
        session_token: session[:customer],
        token_expires_at: Time.now..
      ).first
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!
  layout 'application'

  def show
    @store = current_user.store
  end

  def edit
    @store = current_user.store
  end

  def update
    @store = current_user.store
    if @store.update(store_params)
      service = StripeAccount.new(current_user.account)
      service.update_account_branding
      redirect_to store_path
    else
      render :edit
    end
  end

  private

  def store_params
    params.require(:store).permit(
      :domain,
      :subdomain,
      :primary_color,
      :secondary_color
    )
  end
end

app/helpers/stores/attachments_helper.rb
module Stores::AttachmentsHelper
end

app/helpers/stores/checkouts_helper.rb
module Stores::CheckoutsHelper
end

app/helpers/stores/logins_helper.rb
module Stores::LoginsHelper
end

app/helpers/stores/orders_helper.rb
module Stores::OrdersHelper
end

app/helpers/stores/products_helper.rb
module Stores::ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/edit.html.erb
<form action="<%= store_path(@store) %>" method="post" class="">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <div class="space-y-8">
    <div>
      <div>
        <h3 class="text-lg leading-6 font-medium text-gray-900">Your store</h3>
        <p class="mt-1 text-sm text-gray-500">Where you sell digital products</p>
      </div>

      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-4">
          <label for="subdomain" class="block text-sm font-medium text-gray-700"> Subdomain </label>
          <div class="mt-1 flex rounded-md shadow-sm">
            <input
              type="text"
              name="store[subdomain]"
              id="subdomain"
              value="<%= @store.subdomain %>"
              autocomplete="subdomain" class="flex-1 focus:ring-blue-500 focus:border-blue-500 block w-full min-w-0 rounded-none rounded-l-md sm:text-sm border-gray-300">
            <span class="inline-flex items-center px-3 rounded-r-md border border-l-0 border-gray-300 bg-gray-50 text-gray-500 sm:text-sm">.creatorplatform.xyz/</span>
          </div>
        </div>
      </div>

      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-4">
          <label for="primary_color" class="block text-sm font-medium text-gray-700"> Primary Color </label>
          <div class="mt-1">
            <input
              type="color"
              name="store[primary_color]"
              id="primary_color"
              value="<%= @store.primary_color %>"
              autocomplete="primary_color" class="">
          </div>
        </div>
      </div>

      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-4">
          <label for="secondary_color" class="block text-sm font-medium text-gray-700"> Secondary Color </label>
          <div class="mt-1">
            <input
              type="color"
              name="store[secondary_color]"
              id="secondary_color"
              value="<%= @store.secondary_color %>"
              autocomplete="secondary_color" class="">
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="pt-5">
    <div class="flex justify-end">
      <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">Save</button>
    </div>
  </div>
</form>

app/views/stores/show.html.erb
<%= content_for :page_title do %>
Store
<% end %>

<div class="bg-white shadow overflow-hidden sm:rounded-lg mt-4">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg leading-6 font-medium text-gray-900">Store information</h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500">
      <%= link_to "edit", edit_store_path, class: "underline" %>
    </p>
  </div>
  <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
    <dl class="sm:divide-y sm:divide-gray-200">
      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">View</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= link_to store_root_url(subdomain: @store.subdomain), store_root_url(subdomain: @store.subdomain), class: 'underline' %>
        </dd>
      </div>
      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Subdomain</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @store.subdomain %></dd>
      </div>
      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Primary color</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <span style="background-color: <%= @store.primary_color %>; width: 20px; height: 20px; border-radius: 50%; display: inline-block;"></span>
          <%= @store.primary_color %>
        </dd>
      </div>
      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Secondary color</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <span style="background-color: <%= @store.secondary_color %>; width: 20px; height: 20px; border-radius: 50%; display: inline-block;"></span>
          <%= @store.secondary_color %>
        </dd>
      </div>
    </dl>
  </div>
</div>