config/routes.rb
require 'constraints/domain_constraint'

Rails.application.routes.draw do
  devise_for :users
  post '/webhooks/:source', to: 'webhooks#create'

  constraints DomainConstraint do
    scope module: :stores do
      resources :products
      root to: 'products#index', as: 'store_root'
      resource :checkout, as: 'store_checkout'
      resources :logins
      resources :orders
      resources :attachments
    end
  end

  root 'static_pages#root'

  resource :dashboard
  resources :accounts
  resources :payouts, only: [:create, :index]
  resources :payments, only: [:index, :show]

  resources :products do
    resources :attachments, shallow: true
  end

  resource :store

  resource :checkout
  resources :customers
  resources :cardholders do
    resources :cards, shallow: true do
      resource :ephemeral_key, only: [:show]
    end
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id              :bigint           not null, primary key
#  data            :json
#  description     :text
#  name            :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  stripe_id       :string
#  stripe_price_id :string
#  user_id         :bigint           not null
#
# Indexes
#
#  index_products_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Product < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  belongs_to :user
  has_one :store, through: :user
  has_many :customer_products
  has_many :customers, through: :customer_products
  has_many :attachments, dependent: :destroy

  has_one_attached :photo do |photo|
    photo.variant :thumb, resize_to_limit: [100, 100]
    photo.variant :medium, resize_to_limit: [400, 400]
  end

  def price

    product_data&.default_price&.unit_amount&.fdiv(100.0)
  end

  def product_data
    return if data.blank?
    Stripe::Product.construct_from(JSON.parse(data))
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = current_user.products.order(created_at: :desc)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
  end

  def create
    @product = current_user.products.new(product_params)
    if @product.save
      service = StripeProduct.new(params, @product)
      service.create_product
      redirect_to @product
    else
      render :new
    end
  end

  def edit
  end

  private

  def product_params
    @product_params = params
      .require(:product)
      .permit(:name, :description, :photo)

    @product_params.delete(:photo) if @product_params[:photo].blank?
    @product_params
  end
end

app/controllers/stores/products_controller.rb
module Stores
  class ProductsController < StoreBaseController
    def index
      @products = @store.products
    end

    def show
      @product = @store.products.find(params[:id])
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores/products_helper.rb
module Stores::ProductsHelper
end

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<% content_for :page_title do %>
Products
<% end %>

<div class="">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-semibold text-gray-900"></h1>
      <p class="mt-2 text-sm text-gray-700">A list of all the products in your account.</p>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      <a href="<%= new_product_path %>" class="inline-flex items-center justify-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 sm:w-auto">Add product</a>
    </div>
  </div>
  <div class="mt-8 flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 text-right">Price</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">Edit</span>
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
              <% @products.each do |product| %>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                  <%= link_to product.name, product %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500 text-right">
                  <%= number_to_currency(product.price) %>
                </td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <a href="<%= edit_product_path(product) %>" class="text-blue-600 hover:text-blue-900">Edit<span class="sr-only">, Lindsay Walton</span></a>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<form action="/products" method="post" class="space-y-8 divide-y divide-gray-200" data-turbo="false">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="space-y-8 divide-y divide-gray-200">
    <div>
      <div>
        <h3 class="text-lg leading-6 font-medium text-gray-900">Product</h3>
        <p class="mt-1 text-sm text-gray-500"></p>
      </div>

      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-4">
          <label for="name" class="block text-sm font-medium text-gray-700"> Name </label>
          <div class="mt-1">
            <input type="text" name="product[name]" id="name" class="flex-1 focus:ring-blue-500 focus:border-blue-500 block w-full min-w-0 rounded-md sm:text-sm border-gray-300">
          </div>
        </div>

        <div class="sm:col-span-6">
          <label for="description" class="block text-sm font-medium text-gray-700"> Description </label>
          <div class="mt-1">
            <textarea id="description" name="product[description]" rows="3" class="shadow-sm focus:ring-blue-500 focus:border-blue-500 block w-full sm:text-sm border border-gray-300 rounded-md"></textarea>
          </div>
          <p class="mt-2 text-sm text-gray-500">Write a few sentences to describe the product.</p>
        </div>

        <div class="sm:col-span-6">
          <label for="photo" class="block text-sm font-medium text-gray-700"> Photo </label>
          <div class="mt-1">
            <input type="file" data-direct-upload-url="<%= rails_direct_uploads_url %>" name="product[photo]" class="bg-white py-2 px-3 border border-gray-300 rounded-md shadow-sm text-sm leading-4 font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
          </div>
        </div>
      </div>
    </div>

    <div class="pt-8">
      <div>
        <h3 class="text-lg leading-6 font-medium text-gray-900">Default Price</h3>
        <p class="mt-1 text-sm text-gray-500">Set a default price.</p>
      </div>
      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-3">
          <label for="currency" class="block text-sm font-medium text-gray-700">Currency</label>
          <div class="mt-1">
            <input type="text" value="usd" name="default_price_data[currency]" id="currency" class="shadow-sm focus:ring-blue-500 focus:border-blue-500 block w-full sm:text-sm border-gray-300 rounded-md">
          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="amount" class="block text-sm font-medium text-gray-700">Amount</label>
          <div class="mt-1">
            <input type="number" step="0.01" name="default_price_data[amount]" id="amount" class="shadow-sm focus:ring-blue-500 focus:border-blue-500 block w-full sm:text-sm border-gray-300 rounded-md">
          </div>
        </div>
      </div>
    </div>

    <div data-controller="product-form" class="pt-8">
      <div>
        <h3 class="text-lg leading-6 font-medium text-gray-900">Alternative Prices</h3>
        <p class="mt-1 text-sm text-gray-500">
          Select from the list of supported currencies
          <a href="https://stripe.com/docs/currencies#presentment-currencies"
             class="underline"
            target="_blank">stripe.com/docs/currencies</a>
        </p>
      </div>

      <button data-action="product-form#addPrice" type="button" class="mt-4 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">Add price</button>

      <div data-product-form-target="prices"></div>

      <template data-product-form-target="template">
        <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
          <div class="sm:col-span-3">
            <label for="currency" class="block text-sm font-medium text-gray-700">Currency</label>
            <div class="mt-1">
              <input type="text" name="currency_options[][currency]" id="currency" class="shadow-sm focus:ring-blue-500 focus:border-blue-500 block w-full sm:text-sm border-gray-300 rounded-md">
            </div>
          </div>

          <div class="sm:col-span-3">
            <label for="amount" class="block text-sm font-medium text-gray-700">Amount</label>
            <div class="mt-1">
              <input type="number" step="0.01" name="currency_options[][amount]" id="amount" class="shadow-sm focus:ring-blue-500 focus:border-blue-500 block w-full sm:text-sm border-gray-300 rounded-md">
            </div>
          </div>
        </div>
      </template>
    </div>

  </div>

  <div class="pt-5">
    <div class="flex justify-end">
      <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
        Create Product
      </button>
    </div>
  </div>
</form>

app/views/products/show.html.erb
<%= content_for :page_title do %>
<%= @product.name %>
<% end %>

<div class="flex mt-8">

  <div>
    <% if @product.photo.representation(:medium) %>
      <%= image_tag @product.photo.representation(:medium) %>
    <% end %>
  </div>

  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="flex-auto px-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-xl font-semibold text-gray-900">Attachments</h1>
        <p class="mt-2 text-sm text-gray-700">A list of all the attachments that customers have access to when they buy <%= @product.name %>.</p>
      </div>
      <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      </div>
    </div>
    <div class="mt-8 flex flex-col">
      <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
          <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
            <table class="min-w-full divide-y divide-gray-300">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Views</th>
                  <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                    <span class="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 bg-white">
                <% @product.attachments.each do |attachment| %>
                <tr>
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                    <%= attachment.name %>
                  </td>
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                    <%= attachment.views_count %>
                  </td>
                  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                    <a href="#" class="text-blue-600 hover:text-blue-900">Edit<span class="sr-only">, Lindsay Walton</span></a>
                  </td>
                </tr>
                <% end %>
                <!-- More people... -->
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <form action="<%= product_attachments_path(@product) %>" method="post" class="mt-8">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div>
        <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
        <div class="mt-1">
          <input type="text" name="attachment[name]" id="name" class="shadow-sm focus:ring-blue-500 focus:border-blue-500 block w-full sm:text-sm border-gray-300 rounded-md">
        </div>
      </div>

      <div>
        <label for="file" class="block text-sm font-medium text-gray-700">File</label>
        <div class="mt-1">
          <input type="file" id="file" data-direct-upload-url="<%= rails_direct_uploads_url %>" name="attachment[file]" class="bg-white py-2 px-3 border border-gray-300 rounded-md shadow-sm text-sm leading-4 font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
        </div>
      </div>
      <div class="mt-4">
        <button type="submit" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
          Add Attachment
        </button>
      </div>
    </form>
  </div>
</div>